# Generated by Django 5.0.6 on 2024-06-05 14:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ladder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=30, unique=True, verbose_name='Модель')),
                ('length', models.IntegerField(verbose_name='Длина')),
                ('width', models.IntegerField(verbose_name='Ширина')),
                ('height', models.IntegerField(verbose_name='Высота')),
            ],
            options={
                'verbose_name': 'Лестница',
                'verbose_name_plural': 'Лестницы',
                'ordering': ('serial_number',),
            },
        ),
        migrations.CreateModel(
            name='Pillar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=30, unique=True, verbose_name='Модель')),
                ('length', models.IntegerField(verbose_name='Длина')),
                ('width', models.IntegerField(verbose_name='Ширина')),
                ('height', models.IntegerField(verbose_name='Высота')),
            ],
            options={
                'verbose_name': 'Колонна',
                'verbose_name_plural': 'Колонны',
                'ordering': ('serial_number',),
            },
        ),
        migrations.CreateModel(
            name='Plate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=30, unique=True, verbose_name='Модель')),
                ('length', models.IntegerField(verbose_name='Длина')),
                ('width', models.IntegerField(verbose_name='Ширина')),
                ('height', models.IntegerField(verbose_name='Высота')),
            ],
            options={
                'verbose_name': 'Плита',
                'verbose_name_plural': 'Плиты',
                'ordering': ('serial_number',),
            },
        ),
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True, verbose_name='Наименование')),
                ('industrial', models.BooleanField(default=False, verbose_name='Промышленное')),
                ('pillars_count', models.IntegerField(verbose_name='Кол-во колонн')),
                ('plates_count', models.IntegerField(verbose_name='Кол-во плит')),
                ('ladders_count', models.IntegerField(verbose_name='Кол-во лестниц')),
                ('length', models.IntegerField(verbose_name='Длина')),
                ('width', models.IntegerField(verbose_name='Ширина')),
                ('height', models.IntegerField(verbose_name='Высота')),
                ('floors', models.IntegerField(verbose_name='Этажей')),
                ('ladder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buildings.ladder', verbose_name='Лестница')),
                ('pillar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buildings.pillar', verbose_name='Колонна')),
                ('plate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buildings.plate', verbose_name='Плита')),
            ],
            options={
                'verbose_name': 'Здание',
                'verbose_name_plural': 'Здания',
                'ordering': ('name',),
            },
        ),
    ]
