# Generated by Django 5.0.6 on 2024-06-05 19:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='elevator_heght',
            field=models.IntegerField(default=0, verbose_name='Ширина лифта'),
        ),
        migrations.AddField(
            model_name='building',
            name='elevator_width',
            field=models.IntegerField(default=0, verbose_name='Длина лифта'),
        ),
        migrations.AddField(
            model_name='building',
            name='has_elevator',
            field=models.BooleanField(default=False, verbose_name='Лифт'),
        ),
        migrations.AlterField(
            model_name='building',
            name='floors',
            field=models.IntegerField(verbose_name='Этажи'),
        ),
        migrations.AlterField(
            model_name='building',
            name='ladder',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='buildings.ladder', verbose_name='Лестница'),
        ),
    ]
