# Generated by Django 5.0.6 on 2024-06-05 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0002_building_elevator_heght_building_elevator_width_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='x_step',
            field=models.IntegerField(default=0, verbose_name='Шаг по горизонтали'),
        ),
        migrations.AddField(
            model_name='building',
            name='y_step',
            field=models.IntegerField(default=0, verbose_name='Шаг по горизонтали'),
        ),
    ]
