# Generated by Django 5.0.6 on 2024-06-05 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0003_building_x_step_building_y_step'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='building',
            name='elevator_heght',
        ),
        migrations.AddField(
            model_name='building',
            name='elevator_length',
            field=models.IntegerField(default=0, verbose_name='Длина лифта'),
        ),
        migrations.AlterField(
            model_name='building',
            name='elevator_width',
            field=models.IntegerField(default=0, verbose_name='Ширина лифта'),
        ),
    ]
